jobster/jobster/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

jobster/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('candidate/<int:pk>/', include('candidate.urls', namespace= 'candidate')),
    path('employer/<int:pk>/', include('employer.urls', namespace= 'employer')),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace= 'mpoweradmin')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
 ] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

# handler404 = 'main.views.error_404_view'

main/urls.py
from . import views
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
# from jobster import settings

app_name = 'main'

urlpatterns = [
	path('', views.index, name ='index'),
	path('blog/', views.blog, name ='blog'),
	path('about_us/', views.about_us, name ='about_us'),
	path('pricing/', views.pricing, name ='pricing'),
	path('contact_us/', views.contact_us, name ='contact_us'),
	path('faqs/', views.faqs, name ='faqs'),
	path('signin/', views.signin, name ='signin'),
	path('signup/', views.signup, name ='signup'),
	path('user_login/', views.user_login, name ='user_login'),
	path('admin_login/', views.admin_login, name ='admin_login'),
	path('register/', views.register, name ='register'),
	path('admin_register/', views.admin_register, name ='admin_register'),
    path('subscribe/', views.subscribe, name='subscribe'),
	path('jobs/', views.findjobs, name ='jobs'),
	path('seminars/', views.seminars, name ='seminars'),
	path('companies/', views.companies, name ='companies'),
	path('candidates/', views.candidates, name ='candidates'),
	path('postjob/', views.postjob, name ='postjob'),
    path('get_job/', views.get_job, name='get_job'),
    path('give_feedback/<int:pk>/', views.give_feedback, name='give_feedback'),
    path('give_feed/<int:pk>/', views.give_feed, name='give_feed'),
	path('profile_completion/<int:pk>/', views.profile_completion, name="profilecompletion"),
	path('emp_completion/<int:pk>/', views.emp_completion, name="emp_completion"),
	path('admin_completion/<int:pk>/', views.admin_completion, name="admin_completion"),
	path('admin_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('admin_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('profile_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('profile_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('emp_completion/<int:pk>/get_otp/', views.get_otp, name='eget_otp'),
	path('emp_completion/<int:pk>/post_otp/', views.verify_otp, name='everify_otp'),
	path('singlejob/<int:pk2>/', views.singlejob, name='singlejob'),
	path('singleseminar/<int:pk1>/', views.singleseminar, name='singleseminar'),
	path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('password_reset_confirm/<str:email_encoded>/<str:token>/<str:timestamp>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('singlecompany/<int:pk2>/', views.singlecompany, name='singlecompany'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace = 'mpoweradmin')),
] 

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mpoweradmin/urls.py
from . import views
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mpoweradmin'

urlpatterns = [
	path('cdashboard/', views.dashboard, name='cdashboard'),
	path('inbox_count/', views.inbox_count, name='inbox_count'),
	path('newjob/', views.newjob, name='newjob'),
	path('edit_profile/', views.edit, name='cedit'),
    path('get_ot/', views.get_ot, name='get_ot'),
    path('post_ot/', views.post_ot, name='post_ot'),
    path('cupd_phone/', views.cupd_phone, name='cupd_phone'),
	path('manage_job/', views.manage, name='manage'),
	path('candidates/', views.candidates, name='candidates'),
	path('subscriptions/', views.subscriptions, name='subscriptions'),
	path('change_pass/', views.change_pass, name='change_pass'),
	path('cinbox/', views.cinbox, name='cinbox'),
	path('cinbox/sendmess/', views.sendmess, name="sendmess"),
	path('cinbox/fetch/', views.fetch, name="fetch"),
	path('cinbox/seen/', views.seen, name='seen'),
	path('cinbox/delete/', views.delete_mess, name='delete_mess'),
	path('createthread/', views.createthread, name='createthread'),
	path('cnotifications/', views.cnotifications, name='cnotifications'),
	path('manage_job/cjobapp/', views.jobapp, name='cjobapp'),
	path('edit_job/', views.edit_job, name='edit_job'),
	path('get_candidate', views.get_candidate, name='get_candidate'),
	path('get_job', views.get_job, name='get_job'),
	path('get_cands/', views.get_cands, name='get_cands'),
	path('get_jobs/', views.get_jobs, name='get_jobs'),
	path('cand_suggest/', views.cand_suggest, name='cand_suggest'),
    path('pending_actions/', views.pending_actions, name='pending_actions'),
    path('pending_actions/cjobapp/', views.jobapp, name='cjobapp'),
	path('quiz/cjobapp/', views.jobapp, name='cjobapp'),
	path('show_tests/', views.show_tests, name='show_tests'),
	path('create_test', views.create_test, name='test'),
	path('create_seminar/', views.create_seminar, name='create_seminar'),
	path('schedule/', views.schedule, name='schedule'),
	path('test_info/', views.test_info, name='test_info'),
	path('get_results/', views.get_results, name='get_results'),
    path('schedule_interview/', views.schedule_interview, name='schedule_interview'),
    path('all_interviews/', views.all_interviews, name='all_interviews'),
    path('done/', views.done, name='done'),
    path('interview_panel/', views.interview_panel, name='interview_panel'),
    path('get_link/', views.get_link, name='get_link'),
	path('seminars/', views.seminars, name='seminars'),
    path('mark_cand_provided/', views.mark_cand_provided, name='mark_cand_provided'),
	path('logout/', views.logout, name='clogout'),
	path('mocks/', views.mocks, name='mocks'),
	path('company/', views.company, name='company'),
	path('jobapp/', views.jobapp, name='jobapp'),
	path('mock_info/', views.mock_info, name='mock_info'),
	path('edit_test/', views.edit_test, name='edit_test'),
	path('get_seminar/', views.get_seminar, name='get_seminar'),
	path('under_development/', views.under_development, name='under_development'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mpoweradmin/models.py
from django.db import models

# Create your models here.

mpoweradmin/views.py
from django.shortcuts import render, redirect
from main.models import *
from json import dumps
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages
import re
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from queue import PriorityQueue
import heapq
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
from datetime import date, timedelta, datetime
from django.http import JsonResponse
import PyPDF2
import textract
import random
import string
import pandas as pd
import matplotlib.pyplot as plt
import pyotp
import base64
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from main.utils import send_emails
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords
import json
from django.core.mail import EmailMessage
from jobster import settings
from main.utils import send_emails
from django.db.models import Count
# def get_registered_counts(model, days):
#     registered_counts = []
#     today = date.today()
#     for i in range(days):
#         d = today - timedelta(days=i)
#         count = model.objects.filter(log_id__date_joined__year=d.year, log_id__date_joined__month=d.month, log_id__date_joined__day=d.day).count()
#         registered_counts.append([d, count])
#     return registered_counts
# Create your views here.
def dashboard(request, pk):
    # employers_registered = get_registered_counts(Employer, 365)
    # job_seekers_registered = get_registered_counts(JobSeeker, 365)
    
    # charts_context = {}
    # charts_context['employer_counts'] = dumps([item[1] for item in employers_registered])
    # charts_context['job_seeker_counts'] = dumps([item[1] for item in job_seekers_registered])
    # charts_context['dates'] = dumps([item[0] for item in employers_registered], default=str)
    # print(charts_context)
    # context = Employer.objects.get(eid=pk)
    # jobs = Jobs.objects.filter(eid=pk)
    jobs = Jobs.objects.all()
    context = Admin.objects.get(aid=pk)
    request.session['email'] = context.email
    nums = []
    nums.append(len(jobs))
    # for obj in context:
    #     print(obj.__dict__)






    applics = Application.objects.all()
    nums.append(len(applics))
    # visits = ProfileVisits.objects.filter(user_type="e", e_id=pk)
    all_notis = []
    count=0
    recent_candidates=[]
    num_notif = Notifications.objects.filter(rece_id=context.log_id_id).order_by('-datetime')
    for i in num_notif:
        single_notis={}
        single_notis['notif_type']=i.notif_type
        single_notis['datetime']=i.datetime
        user=JobSeeker.objects.get(log_id=i.send_id)
        single_notis['name']=user.name
        single_notis['user_id']=user.user_id
        single_notis['log_id']=user.log_id.log_id
        heapq.heappush(recent_candidates, (i.datetime, user.user_id, user.photo, user.name, user.location, user.log_id.log_id))
        # recent_candidates.put([i.datetime, user.user_id, user.photo, user.name, user.title, user.location])
        # if i.job_id:
        #     job=jobs.filter(jobid=i.job_id.jobid)
        #     single_notis['title']=job[0].title
        #     single_notis['jobid']=job[0].jobid
        # if i.testuser_id:
        #     testinfo=TestInfo.objects.get(test_id=i.testuser_id.test_id)
        #     single_notis['test_name']=testinfo.test_name
        #     single_notis['test_id']=i.testuser_id.testuser_id
        all_notis.append(single_notis)
        count=count+1
        if(count>10):
            break
    threads = Threads.objects.filter(sender=context.log_id)
    countunmess=0
    recent_mess=[]
    # for i in applics:
    #     jobseek=JobSeeker.objects.get(user_id=i.user_id.user_id)
    #     heapq.heappush(recent_candidates, (i.date_applied, jobseek.user_id, jobseek.photo, jobseek.name, jobseek.title, jobseek.location))
    for i in threads:
        mess=Messages.objects.filter(msg_id=i.msg_id, receiver_user=context.log_id.log_id).order_by("-date")
        if(len(mess)>0):
            countunmess=countunmess+len(mess.filter(is_read=0))
            tempval=[]
            tempval.append(mess[0].date)
            tempval.append(mess[0].body)
            jobseek=JobSeeker.objects.get(log_id=mess[0].sender_user.log_id)
            tempval.append(jobseek.name)
            tempval.append(jobseek.photo)
            heapq.heappush(recent_candidates, (mess[0].date, jobseek.user_id, jobseek.photo, jobseek.name, jobseek.location, jobseek.log_id.log_id))
            # recent_candidates.put([mess[0].date, jobseek.user_id, jobseek.photo, jobseek.name, jobseek.title, jobseek.location])
            recent_mess.append(tempval)
    finalrecent=[]
    count=0
    existing=[]
    while recent_candidates:
        temp=recent_candidates.pop()
        if temp[1] not in existing:
            finalrecent.append(temp)
            count=count+1
            if(count>10):
                break
        existing.append(temp[1])
    recent_mess.sort(reverse=True)
    recent_mess_temp=[]
    idx=min(4, len(recent_mess))
    for i in range(0, idx):
        recent_mess_temp.append(recent_mess[i])
    applics_chart=[]
    applics_7=[]
    applics_30=[]
    applics_60=[]
    applics_90=[]
    applics_365=[]
    counts=[]
    cou=0

    # visits_chart=[]
    # visits_7=[]
    # visits_30=[]
    # visits_60=[]
    # visits_90=[]
    # visits_365=[]
    # countsv=[]
    # couv=0

    jobs_chart = []
    jobs_7 = []
    jobs_30 = []
    jobs_60 = []
    jobs_90 = []
    jobs_365 = []
    countsj = []
    couj = 0
    for i in range(0, 365):
        d=date.today()-timedelta(days=i)
        temp = applics.filter(date_applied__year=d.year, date_applied__month=d.month, date_applied__day=d.day)
        n=len(temp)
        heapq.heappush(applics_chart, (-1*(n), n, d))
        cou=cou+n
    #     temp = visits.filter(visiting_time__year=d.year, visiting_time__month=d.month, visiting_time__day=d.day)
    #     n=len(temp)
    #     heapq.heappush(visits_chart, (-1*(n), n, d))
    #     couv=couv+n
        temp = jobs.filter(postdate__year=d.year,postdate__month=d.month, postdate__day=d.day)
        n = len(temp)
        heapq.heappush(jobs_chart, (-1*(n), n, d))
        couj = couj+n
        if(len(jobs_chart)==7):
            counts.append(cou)
    #         countsv.append(couv)
            countsj.append(couj)
            for j in range(0, 7):
                applics_7.append([applics_chart[j][2], applics_chart[j][1]])
    #             visits_7.append([visits_chart[j][2], visits_chart[j][1]])
                jobs_7.append([jobs_chart[j][2],jobs_chart[j][1]])

        if(len(jobs_chart)==30):
            counts.append(cou)
    #         countsv.append(couv)
            countsj.append(couj)

            for j in range(0, 7):
                applics_30.append([applics_chart[j][2], applics_chart[j][1]])
    #             visits_30.append([visits_chart[j][2], visits_chart[j][1]])
                jobs_30.append([jobs_chart[j][2],jobs_chart[j][1]])

        if(len(jobs_chart)==60):
            counts.append(cou)
    #         countsv.append(couv)
            countsj.append(couj)

            for j in range(0, 7):
                applics_60.append([applics_chart[j][2], applics_chart[j][1]])
    #             visits_60.append([visits_chart[j][2], visits_chart[j][1]])
                jobs_60.append([jobs_chart[j][2],jobs_chart[j][1]])

        if(len(jobs_chart)==90):
            counts.append(cou)
    #         countsv.append(couv)
            countsj.append(couj)

            for j in range(0, 7):
                applics_90.append([applics_chart[j][2], applics_chart[j][1]])
    #             visits_90.append([visits_chart[j][2], visits_chart[j][1]])
                jobs_90.append([jobs_chart[j][2],jobs_chart[j][1]])

        if(len(jobs_chart)==364):
            counts.append(cou)
    #         countsv.append(couv)
            countsj.append(couj)

            for j in range(0, 7):
                applics_365.append([applics_chart[j][2], applics_chart[j][1]])
    #             visits_365.append([visits_chart[j][2], visits_chart[j][1]])
                jobs_365.append([jobs_chart[j][2],jobs_chart[j][1]])

    applics_7.sort()
    applics_30.sort()
    applics_60.sort()
    applics_90.sort()
    applics_365.sort()
    # visits_7.sort()
    # visits_30.sort()
    # visits_60.sort()
    # visits_90.sort()
    # visits_365.sort()
    # charts_context={}
    ##################################################################################
    jobs_7.sort()
    jobs_30.sort()
    jobs_60.sort()
    jobs_90.sort()
    jobs_365.sort()
    charts_context = {}
    charts_context['pastsev'] = dumps([item[1] for item in jobs_7])
    charts_context['dates'] = dumps(
        [item[0] for item in jobs_7], default=str)
    charts_context['count_7'] = dumps(countsj[0])
    charts_context['pastthi'] = dumps([item[1] for item in jobs_30])
    charts_context['dates30'] = dumps(
        [item[0] for item in jobs_30], default=str)
    charts_context['count_30'] = dumps(countsj[1])
    charts_context['pastsix'] = dumps([item[1] for item in jobs_60])
    charts_context['dates60'] = dumps(
        [item[0] for item in jobs_60], default=str)
    charts_context['count_60'] = dumps(countsj[2])
    charts_context['pastnin'] = dumps([item[1] for item in jobs_60])
    charts_context['dates90'] = dumps(
        [item[0] for item in jobs_60], default=str)
    charts_context['count_90'] = dumps(countsj[3])
    charts_context['pastyea'] = dumps([item[1] for item in jobs_365])
    charts_context['dates365'] = dumps(
        [item[0] for item in jobs_365], default=str)
    charts_context['count_365'] = dumps(countsj[4])
    
    ##################################################################################
    charts_context['vpastsev']=dumps([item[1] for item in applics_7])

mpoweradmin/templates/create_quiz-employer.html
{% extends 'employer-index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>mpower - Company dashboard - Create test</title>
{% endblock %}
{% block content %}

<style>
   .pxp-dashboard-content-details form .form-control, .pxp-dashboard-content-details form .form-select {
    padding:0.5rem;
   }
</style>
<div class="pxp-dashboard-content-details">
    <h1>Create test</h1>
    <p class="pxp-text-light">Create a test for a evaluating candidates.</p>
    <form method="post">
        {% csrf_token %}
        <div class="mt-4 mt-lg-5">
            <div class="row justify-content-between align-content-center">
                <div class="col-auto order-1 order-sm-2">
                    <div class="pxp-company-dashboard-jobs-search mb-3" style="align-items: flex-start; flex-direction: column">
                        <div class="pxp-company-dashboard-jobs-search-search-form" style="display: flex; align-items: center">
                            <div style="margin-right: 4px; width: 16rem">
                                Name: 
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Enter name" name="name" required>
                            </div>
                        </div>
                        <div style="display: flex; align-items: baseline">
                        <div class="pxp-company-dashboard-jobs-search-search-form mt-3" style="display: flex; align-items: center">
                            <div style="margin-right: 4px; width: 16rem">
                                Time limit (minutes): 
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Enter time" name="timelimit" required>
                            </div>
                        </div>
                        
                    </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
            </div>
        </div>
        <hr />
        <div id="quiz">
            <div class="queswithopt">
                <div class="singlequestion">
                    <div class="questondesc" style="display: flex; align-items: baseline">
                        Q. &nbsp;<input type="text" class="form-control" name="desc" placeholder="Question" required/>
                    </div>
                </div>
                <div class="options" style="display: flex; flex-wrap: wrap; justify-content: space-around">
                    <div class="questondesc col-5 mt-1" style="display: flex; align-items: baseline">
                        <span style="width: 6rem">Option 1. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>
                    </div>
                    <div class="questondesc col-5 mt-1" style="display: flex; align-items: baseline">
                        <span style="width: 6rem">Option 2. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>
                    </div>
                    <div class="questondesc col-5 mt-1" style="display: flex; align-items: baseline">
                        <span style="width: 6rem">Option 3. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>
                    </div>
                    <div class="questondesc col-5 mt-1" style="display: flex; align-items: baseline">
                        <span style="width: 6rem">Option 4. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>
                    </div>
                </div>
                <div class="pxp-company-dashboard-jobs-bulk-actions mb-3 col-5">
                    <div>
                        Answer: 
                    </div>
                    <select class="form-select" name="correct">
                        <option value=1>Option 1</option>
                        <option value=2>Option 2</option>
                        <option value=3>Option 3</option>
                        <option value=4>Option 4</option>
                    </select>
                </div>
            </div>
            <hr />
        </div>
    
    <div class="pxp-company-dashboard-jobs-bulk-actions mb-3 gap-3 mt-3" id="ext" style="align-items: flex-start">
    <button class="btn" onclick="addques()" style="padding: 0.5rem">Add Question</button>
    <div class="pxp-company-dashboard-jobs-bulk-actions mb-3">
        <button class="btn btn-primary" type="submit" style="padding: 0.5rem">Create Test</button>
    </div>
    </div>
</form>
</div>

{% endblock content%}

{% block script %}
$(document).ready(function () {
$('#cdas').removeClass('pxp-active');
$('#cedi').removeClass('pxp-active');
$('#cnew').removeClass('pxp-active');
$('#cman').removeClass('pxp-active');
$('#ccan').removeClass('pxp-active');
$('#csub').removeClass('pxp-active');
$('#ccha').removeClass('pxp-active');
$('#cinb').removeClass('pxp-active');
$('#cnot').removeClass('pxp-active');
$('#scn').removeClass('pxp-active');
$('#qui').addClass('pxp-active');
$('#inr').removeClass('pxp-active');
$('#pen').removeClass('pxp-active');
})

function removeques()
{
    let div=document.getElementsByClassName('queswithopt');
    $('.queswithopt').last().remove();
    $('#quiz').children().last().remove();
    if(div.length==1)
    {
        $('#questremove').remove();
    }
}

function addques()
{
    let div=document.createElement('div');
    div.setAttribute('class', 'queswithopt')
    let quesdiv=document.createElement('div');
    quesdiv.setAttribute('class', 'singlequestion');
    let descdiv=document.createElement('div');
    descdiv.setAttribute('class', 'questondesc');
    descdiv.setAttribute('style', 'display: flex; align-items: baseline');
    descdiv.innerHTML='Q. &nbsp;<input type="text" class="form-control" name="desc" placeholder="Question" required/>';
    quesdiv.append(descdiv);
    div.append(quesdiv);
    let optdiv=document.createElement('div');
    optdiv.setAttribute('class', 'options');
    optdiv.setAttribute('style', 'display: flex; flex-wrap: wrap; justify-content: space-around');
    let optdescdiv=document.createElement('div');
    optdescdiv.setAttribute('class', 'questondesc col-5 mt-1');
    optdescdiv.setAttribute('style', 'display: flex; align-items: baseline')
    optdescdiv.innerHTML='<span style="width: 6rem">Option 1. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>';
    optdiv.append(optdescdiv);
    let optdescdiv2=document.createElement('div');
    optdescdiv2.setAttribute('class', 'questondesc col-5 mt-1');
    optdescdiv2.setAttribute('style', 'display: flex; align-items: baseline')
    optdescdiv2.innerHTML='<span style="width: 6rem">Option 2. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>';
    optdiv.append(optdescdiv2);
    let optdescdiv3=document.createElement('div');
    optdescdiv3.setAttribute('class', 'questondesc col-5 mt-1');
    optdescdiv3.setAttribute('style', 'display: flex; align-items: baseline')
    optdescdiv3.innerHTML='<span style="width: 6rem">Option 3. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>';
    optdiv.append(optdescdiv3);
    let optdescdiv4=document.createElement('div');
    optdescdiv4.setAttribute('class', 'questondesc col-5 mt-1');
    optdescdiv4.setAttribute('style', 'display: flex; align-items: baseline')
    optdescdiv4.innerHTML='<span style="width: 6rem">Option 4. &nbsp;</span><input type="text" class="form-control" name="optdesc" placeholder="Option" required/>';
    optdiv.append(optdescdiv4);
    div.append(optdiv);
    let corrans=document.createElement('div');
    corrans.setAttribute('class', 'pxp-company-dashboard-jobs-bulk-actions mb-3');
    corrans.setAttribute('style', 'width: 25rem');
    let textans=document.createElement('div');
    textans.setAttribute('style', 'width: 13rem');
    textans.innerHTML="Correct answer:"
    corrans.append(textans);
    let select=document.createElement('select');
    select.setAttribute('class', 'form-select');
    select.setAttribute('name', 'correct');
    let option=document.createElement('option');
    option.setAttribute('value', 1);
    option.innerHTML="Option 1";
    select.append(option);
    let option2=document.createElement('option');
    option2.setAttribute('value', 2);
    option2.innerHTML="Option 2";
    select.append(option2);
    let option3=document.createElement('option');
    option3.setAttribute('value', 3);
    option3.innerHTML="Option 3";
    select.append(option3);
    let option4=document.createElement('option');
    option4.setAttribute('value', 4);
    option4.innerHTML="Option 4";
    select.append(option4);
    corrans.append(select);
    div.append(corrans);
    let hr=document.createElement('hr');
    let maindiv=document.getElementById('quiz');
    quiz.append(div);
    let removediv=document.createElement('div');
    removediv.setAttribute('class', 'pxp-company-dashboard-jobs-bulk-actions mb-3');
    removediv.setAttribute('id', 'questremove');
    let delbut=document.createElement('button');
    delbut.setAttribute('class', 'btn');
    delbut.setAttribute('onclick', 'removeques()');
    delbut.setAttribute('style', 'padding: 0.5rem');
    delbut.innerHTML="Remove Question";
    removediv.append(delbut);
    quiz.append(hr);
    let externdiv=document.getElementById('ext');
    let allque=document.getElementsByClassName('queswithopt');
    console.log(allque.length);
    if(allque.length==2)
    {
        externdiv.append(removediv);
    }
}

{% endblock %}

mpoweradmin/templates/under_develop.html
{% load static %}
<!doctype html>
<html lang="en" class="pxp-root">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">

        <title>mpower - 404</title>
    </head>
    <body>
        <div class="pxp-preloader"><span>Loading...</span></div>

        <section class="mt-100 pxp-no-hero">
            <div class="pxp-container">
                <h2 class="pxp-section-h2 text-center">This page is under development</h2>
                <div class="pxp-404-fig text-center mt-4 mt-lg-5">
                    <img src="{% static 'images/underconstruction.png' %}" alt="Page not found">
                </div>

                <div class="mt-4 mt-lg-5 text-center">
                    <a href="{% url 'employer:cdashboard' pk=pk %}" class="btn rounded-pill pxp-section-cta">Go to dashboard<span class="fa fa-angle-right"></span></a>
                </div>
            </div>
        </section>

        
        

        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/nav.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>