employer/urls.py
from . import views
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'employer'

urlpatterns = [
	path('', views.dashboard, name='cdashboard'),
	path('inbox_count/', views.inbox_count, name='inbox_count'),
	path('newjob/', views.newjob, name='newjob'),
	path('edit_profile/', views.edit, name='cedit'),
    path('get_ot/', views.get_ot, name='get_ot'),
    path('post_ot/', views.post_ot, name='post_ot'),
    path('cupd_phone/', views.cupd_phone, name='cupd_phone'),
	path('manage_job/', views.manage, name='manage'),
	path('candidates/', views.candidates, name='candidates'),
	path('subscriptions/', views.subscriptions, name='subscriptions'),
	path('change_pass/', views.change_pass, name='change_pass'),
	path('cinbox/', views.cinbox, name='cinbox'),
	path('cinbox/sendmess/', views.sendmess, name="sendmess"),
	path('cinbox/fetch/', views.fetch, name="fetch"),
	path('cinbox/seen/', views.seen, name='seen'),
	path('cinbox/delete/', views.delete_mess, name='delete_mess'),
	path('createthread/', views.createthread, name='createthread'),
	path('cnotifications/', views.cnotifications, name='cnotifications'),
	path('manage_job/cjobapp/', views.jobapp, name='cjobapp'),
	path('edit_job/', views.edit_job, name='edit_job'),
	path('get_candidate', views.get_candidate, name='get_candidate'),
	path('get_cands/', views.get_cands, name='get_cands'),
	path('cand_suggest/', views.cand_suggest, name='cand_suggest'),
    path('pending_actions/', views.pending_actions, name='pending_actions'),
    path('pending_actions/cjobapp/', views.jobapp, name='cjobapp'),
	path('quiz/cjobapp/', views.jobapp, name='cjobapp'),
	path('show_tests/', views.show_tests, name='show_tests'),
	path('create_test', views.create_test, name='test'),
	path('schedule/', views.schedule, name='schedule'),
	path('test_info/', views.test_info, name='test_info'),
	path('get_results/', views.get_results, name='get_results'),
    path('schedule_interview/', views.schedule_interview, name='schedule_interview'),
    path('all_interviews/', views.all_interviews, name='all_interviews'),
	path('all_templates/', views.all_templates, name='all_templates'),
    path('create_temp/', views.create_temp, name='create_temp'),
    path('get_template/', views.get_template, name='get_template'),
	path('schedule_temp/', views.schedule_temp, name='schedule_temp'),
    path('edit_template/<int:pk2>/', views.edit_template, name='edit_template'),
    path('get_temp_details/', views.get_temp_details, name='get_temp_details'),
    path('get_all_steps/<int:pk2>/', views.get_all_steps, name='get_all_steps'),
    path('delastep/<int:pk2>/', views.delastep, name='delastep'),
    path('all_steps/', views.all_steps, name='all_steps'),
    path('create_step/', views.create_step, name='create_step'),
    path('get_step/', views.get_step, name='get_step'),
    path('edit_step/', views.edit_step, name='edit_step'),
    path('done/', views.done, name='done'),
    path('get_link/', views.get_link, name='get_link'),
	path('logout/', views.logout, name='clogout'),
	path('suggest/', views.suggest, name='suggest'),
	path('request_cand/', views.requestCand, name='requestCand'),
	path('interview_complete/', views.interview_complete, name='interview_complete'),
	path('panel_request/', views.panel_request, name='panel_request'),
	path('edit_test/', views.edit_test, name='edit_test'),
	path('resume_feedback/', views.resume_feedback, name='resume_feedback'),
	path('get_cand_name/', views.get_cand_name, name='get_cand_name'),
	path('matchPerChange/', views.matchPerChange, name='matchPerChange'),
	path('resume_link/', views.resume_link, name='resume_link'),
	path('screening_questions/', views.screening_questions, name='screening_questions'),
	path('under_development/', views.under_development, name='under_development'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobster/jobster/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

jobster/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('candidate/<int:pk>/', include('candidate.urls', namespace= 'candidate')),
    path('employer/<int:pk>/', include('employer.urls', namespace= 'employer')),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace= 'mpoweradmin')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
 ] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

# handler404 = 'main.views.error_404_view'

main/urls.py
from . import views
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
# from jobster import settings

app_name = 'main'

urlpatterns = [
	path('', views.index, name ='index'),
	path('blog/', views.blog, name ='blog'),
	path('about_us/', views.about_us, name ='about_us'),
	path('pricing/', views.pricing, name ='pricing'),
	path('contact_us/', views.contact_us, name ='contact_us'),
	path('faqs/', views.faqs, name ='faqs'),
	path('signin/', views.signin, name ='signin'),
	path('signup/', views.signup, name ='signup'),
	path('user_login/', views.user_login, name ='user_login'),
	path('admin_login/', views.admin_login, name ='admin_login'),
	path('register/', views.register, name ='register'),
	path('admin_register/', views.admin_register, name ='admin_register'),
    path('subscribe/', views.subscribe, name='subscribe'),
	path('jobs/', views.findjobs, name ='jobs'),
	path('seminars/', views.seminars, name ='seminars'),
	path('companies/', views.companies, name ='companies'),
	path('candidates/', views.candidates, name ='candidates'),
	path('postjob/', views.postjob, name ='postjob'),
    path('get_job/', views.get_job, name='get_job'),
    path('give_feedback/<int:pk>/', views.give_feedback, name='give_feedback'),
    path('give_feed/<int:pk>/', views.give_feed, name='give_feed'),
	path('profile_completion/<int:pk>/', views.profile_completion, name="profilecompletion"),
	path('emp_completion/<int:pk>/', views.emp_completion, name="emp_completion"),
	path('admin_completion/<int:pk>/', views.admin_completion, name="admin_completion"),
	path('admin_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('admin_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('profile_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('profile_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('emp_completion/<int:pk>/get_otp/', views.get_otp, name='eget_otp'),
	path('emp_completion/<int:pk>/post_otp/', views.verify_otp, name='everify_otp'),
	path('singlejob/<int:pk2>/', views.singlejob, name='singlejob'),
	path('singleseminar/<int:pk1>/', views.singleseminar, name='singleseminar'),
	path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('password_reset_confirm/<str:email_encoded>/<str:token>/<str:timestamp>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('singlecompany/<int:pk2>/', views.singlecompany, name='singlecompany'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace = 'mpoweradmin')),
] 

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Emp_Manage(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True, blank=True),
    ename = models.CharField(max_length=100, default=None, null=True)
    etype = models.CharField(max_length=100, default=None, null=True)
    address = models.CharField(max_length=200, default=None, null=True)
    phone = models.CharField(max_length=100, default=None, null=True)
    logo = models.ImageField(upload_to='logos/', default=None, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    yearfounded = models.CharField(max_length=10, default=None, null=True)

employer/templates/edit-template-employer.html
{% extends 'employer-index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>mpower - Company dashboard - Edit template</title>
{% endblock %}
{% block content %}

<div class="pxp-dashboard-content-details">
    <h1>Edit template</h1>
    <p class="pxp-text-light">Edit template according to onboarding procedure.</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row mt-4 mt-lg-5">
            <div class="mb-3">
                <label for="pxp-company-name" class="form-label"><h5>Template name</h5></label>
                <input type="text" id="pxp-company-name" class="form-control" placeholder="Template name" name="templ_name" value="{{ template.template_name }}">
            </div>
        </div>
        <hr/>
        <div class="mb-3">
            <label for="pxp-company-about" class="form-label"><h5>Description</h5></label>
            <textarea class="form-control" id="pxp-company-about" placeholder="Description" name="templ_desc">{{ template.template_description }}</textarea>
        </div>
        <div class="mt-lg-5">
            <button class="btn rounded-pill pxp-section-cta">Edit template</button>
        </div>
    </form>
    <hr/>
    <div class="mb-3">
        <label for="pxp-company-about" class="form-label"><h5>All steps</h5></label>
    </div>
    <div class="mt-4 mt-lg-5">
        <div class="table-responsive">
            <table class="table align-middle">
                <th style="width: 10%">Order</th>
                <th style="width: 40%">Name</th>
                <th style="width: 25%">Description</th>
                {% for i in steps %}
                <tr>
                    <td style="width: 10%;"><div class="pxp-candidate-dashboard-experience-company">{{ forloop.counter }}</div></td>
                    <td style="width: 40%;"><div class="pxp-candidate-dashboard-experience-company">{{ i.step_id.step_name }}</div></td>
                    <td style="width: 25%;"><div class="pxp-candidate-dashboard-experience-company">{{ i.step_id.step_description }}</div></td>
                    <td>
                        <div class="pxp-dashboard-table-options">
                            <ul class="list-unstyled">
                                <li><button title="Delete" class="delete_exp" onclick="delastep({{ i.step_id.step_id }})"><input style="display: none" value={{ i.step_id.step_id }} /><span class="fa fa-trash-o"></span></button></li>
                            </ul>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <button class="btn rounded-pill pxp-section-cta" data-bs-target="#pxp-tempshow-modal" data-bs-toggle="modal" onclick="addsteptotemp()">Add step</button>
    <hr/>
</div>



<div class="modal fade pxp-user-modal" id="pxp-tempshow-modal" aria-hidden="true" aria-labelledby="feedbackModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered widthadjuster" style="justify-content: center">
        <div class="modal-content" style="width: 35rem">
            <div class="modal-header" style="padding: 10px; flex-direction: column">
                <h4 id="name_of_temp">Available steps to add</h4>
            </div>
            <hr style="margin: 0px" />
            <div class="modal-body" style="padding: 1rem !important">
                <div class="pxp-company-dashboard-jobs-bulk-actions" style="margin-left: auto; flex-direction: column">
                    <div id="addstepshere" style="width: 100%; display: flex; flex-direction: column;">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content%}


{% block script %}
$(document).ready(function () {
    $('#cdas').removeClass('pxp-active');
    $('#cedi').removeClass('pxp-active');
    $('#cnew').removeClass('pxp-active');
    $('#cman').removeClass('pxp-active');
    $('#ccan').removeClass('pxp-active');
    $('#csub').removeClass('pxp-active');
    $('#ccha').removeClass('pxp-active');
    $('#cinb').removeClass('pxp-active');
    $('#cnot').removeClass('pxp-active');
    $('#scn').removeClass('pxp-active');
    $('#qui').removeClass('pxp-active');
    $('#inr').removeClass('pxp-active');
    $('#pen').removeClass('pxp-active');
    $('#templ').addClass('pxp-active');
    $('#step').removeClass('pxp-active');
})

function addsteptotemp()
{
    $.ajax(
        {
            type:"GET",
            url: "{% url 'employer:get_all_steps' pk=pk pk2=pk2 %}",
                data:{
                },
            success: function( data ) 
            {
                let final_data=JSON.parse(data['info']);
                let inserter=document.getElementById('addstepshere');
                inserter.innerHTML='';
                for(let i=0;i<final_data.length;i++)
                {
                    let div=document.createElement('div');
                    div.setAttribute('class', 'spacematch mt-4')
                    div.setAttribute('style', 'display: flex; justify-content: space-between;')
                    let p=document.createElement('p');
                    p.innerHTML=final_data[i].step_name;
                    div.append(p);
                    let but=document.createElement('button');
                    but.setAttribute('class', 'btn rounded-pill pxp-section-cta')
                    let finalstring='finaladd('+final_data[i].step_id+')'
                    but.setAttribute('onclick', finalstring)
                    but.innerHTML="Add"
                    div.append(but);
                    inserter.append(div);
                }
            }
        })
}

function finaladd(id)
{
    $.ajax(
        {
            type:"POST",
            url: "{% url 'employer:get_all_steps' pk=pk pk2=pk2 %}",
            data:{
                    'step_id': id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function( data ) 
            {
                location.reload()
            }
    })
}

function delastep(id)
{
    $.ajax(
        {
            type:"POST",
            url: "{% url 'employer:delastep' pk=pk pk2=pk2 %}",
            data:{
                    'step_id': id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function( data ) 
            {
                location.reload()
            }
    })
}
{% endblock %}

employer/templates/emp_add.html
{% extends 'emp_base.html' %}

{% block title %}
<title>mpower - Manage Employers</title>
{% endblock %}

{% block content %}

<p class="text-center mt-3">
  <a href="all_emp" class="btn btn-primary">Show All Employers</a>
</p>

<div class="container mt-5">
     <form class="col-6 mx-auto p-3 card shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
         <h2>Add Employer</h2>
         <hr>

         <div class="mb-3">
          <label for="ename" class="form-label">Employer Name</label>
          <input type="text" class="form-control" name="ename">
        </div>

        <div class="mb-3">
          <label for="etype" class="form-label">Employer Industry</label>
          <input type="text" class="form-control" name="etype">
        </div>

        <div class="mb-3">
          <label for="eaddress" class="form-label">Employer Address</label>
          <input type="text" class="form-control" name="address">
        </div>

        <div class="mb-3">
          <label for="ephn" class="form-label">Employer Phone no</label>
          <input type="text" class="form-control" name="phone">
        </div>

        <div class="form-group mb-3">
            <label for="logo">Employer logo Image</label>
            <input name="logo" type="file" class="form-control">
        </div>

        <div class="mb-3">
            <label for="website" class="form-label">Employer Website</label>
            <input type="text" class="form-control" name="website">
        </div>

        <div class="mb-3">
            <label for="yearfounded" class="form-label">Year Founded</label>
            <input type="number" class="form-control" name="yearfounded">
        </div>
  
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
 </div>
{% endblock %}

employer/templates/quiz-employer.html
{% extends 'employer-index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>mpower - Company dashboard - Quiz</title>
{% endblock %}
{% block content %}
<div class="pxp-dashboard-content-details">
    <h1>Quiz</h1>
    <p class="pxp-text-light">Quizzes created for jobs.</p>
    <div class="mt-4 mt-lg-5">
        <div class="row justify-content-between align-content-center">
            <div class="col-auto order-2 order-sm-1">
                <div class="pxp-company-dashboard-jobs-bulk-actions mb-3">
                    <select class="form-select" name="act">
                        <option value="a">Bulk actions</option>
                        {% comment %} <option>Edit</option> {% endcomment %}
                        <option value="b">Delete</option>
                    </select>
                    <button class="btn ms-2" onclick="multiple()">Apply</button>
                </div>
            </div>
            <div class="col-auto order-1 order-sm-2">
                <div class="pxp-company-dashboard-jobs-search mb-3">
                    <div class="pxp-company-dashboard-jobs-search-results me-3">{{ count }} Quizzes</div>
                    <div class="pxp-company-dashboard-jobs-bulk-actions"><a href="{% url 'employer:create_quiz' pk %}" class="btn ms-2">Create quiz</a></div>
                    <div class="pxp-company-dashboard-jobs-search-search-form">
                        <div class="input-group">
                            <span class="input-group-text" style="background: white"><span class="fa fa-search"></span></span>
                            <input type="text" class="form-control" placeholder="Search quizzes..." id="search">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle" id="table">
                <thead>
                    <tr>
                        <th class="pxp-is-checkbox" style="width: 1%;"><input type="checkbox" onClick="toggle(this)" class="form-check-input" name="all"></th>
                        <th style="width: 25%;">Job</th>
                        <th style="width: 20%;">Category</th>
                        <th style="width: 12%;">Type</th>
                        <th>Date of Creation<span class="fa fa-angle-up ms-3"></span></th>
                        <th style="width: 15%;">Time limit</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in pe %}
                    <tr>
                        <td><input type="checkbox" name="chek" class="form-check-input" value={{ i.jobid }}></td>
                        <td>
                            <a href="#">
                                <div class="pxp-company-dashboard-job-title" onclick="loadermodal('{{i.jobid}}')" data-bs-target="#pxp-job-modal" data-bs-toggle="modal">{{ i.title }}</div>
                                <div class="pxp-company-dashboard-job-location"><span class="fa fa-globe me-1"></span>{{ i.location }}</div>
                            </a>
                        </td>
                        <td><div class="pxp-company-dashboard-job-category">{{ i.fnarea }}</div></td>
                        <td><div class="pxp-company-dashboard-job-type">{{ i.jobtype }}</div></td>
                        <td>
                            <div class="pxp-company-dashboard-job-date mt-1">{{ i.created_date }}</div>
                        </td>
                        <td><a class="pxp-company-dashboard-job-applications">{{ i.time_limit }} Minutes</a></td>
                        <td>
                            <div class="pxp-dashboard-table-options">
                                <ul class="list-unstyled">
                                    <li><button onclick="loadermodal('{{i.jobid}}')" data-bs-target="#pxp-job-modal" data-bs-toggle="modal" title="Preview"><span class="fa fa-eye"></span></button></li>
                                    <input style="display: none" value={{i.jobid}}>
                                    <li><button title="Delete" onclick="delfav({{i.jobid}})"><span class="fa fa-trash-o"></span></button></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="row mt-4 mt-lg-5 justify-content-between align-items-center">
                <div class="col-auto">
                    <nav class="mt-3 mt-sm-0" aria-label="Jobs list pagination">
                        <ul class="pagination pxp-pagination">
                            {% if count >= 11 %}
                            {% if pe.has_previous %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{pe.previous_page_number}}" class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{pe.previous_page_number}}" class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                {% endif %}
                            {% endif %}

                            {% if pe.number|add:'-4' > 1 %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.number|add:'-5' }}" class="page-link">&hellip;</a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{ pe.number|add:'-5' }}" class="page-link">&hellip;</a></li>
                                {% endif %}
                            {% endif %}

                            {% for i in pe.paginator.page_range %}
                                {% if pe.number == i %}
                                    <li class="page-item active" aria-current="page">
                                        <span style="padding: 0.7rem" class="page-link">{{pe.number}}</span>
                                    </li>
                                {% elif i > pe.number|add:'-5' and i < pe.number|add:'5' %}
                                    {% if GET_params %}
                                    <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ i }}" class="page-link">{{i}}</a></li>
                                    {% else %}
                                    <li class="page-item"><a style="padding: 0.7rem" href="?page={{ i }}" class="page-link">{{i}}</a></li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}

                            {% if pe.paginator.num_pages > pe.number|add:'4' %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.number|add:'5' }}" class="page-link">&hellip;</a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{ pe.number|add:'5' }}" class="page-link">&hellip;</a></li>
                                {% endif %}
                            {% endif %}

                            {% if pe.has_next %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.next_page_number }}" class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{pe.next_page_number}}" class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                {% endif %}
                            {% endif %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-auto">
                    {% comment %} <a href="#" class="btn rounded-pill pxp-section-cta mt-3 mt-sm-0">Show me more<span class="fa fa-angle-right"></span></a> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

{% block script %}
$(document).ready(function () {
$('#cdas').removeClass('pxp-active');
$('#cedi').removeClass('pxp-active');
$('#cnew').removeClass('pxp-active');
$('#cman').removeClass('pxp-active');
$('#ccan').removeClass('pxp-active');
$('#csub').removeClass('pxp-active');
$('#ccha').removeClass('pxp-active');
$('#cinb').removeClass('pxp-active');
$('#cnot').removeClass('pxp-active');
$('#scn').removeClass('pxp-active');
$('#qui').addClass('pxp-active');
$('#inr').removeClass('pxp-active');
$('#pen').removeClass('pxp-active');
$('#templ').removeClass('pxp-active');
$('#step').removeClass('pxp-active');
})

var $rows = $('#table tbody tr');
$('#search').keyup(function() {
    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
    $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
});
$("[name='chek']").change(function(){
    let a=0;
    checkboxes = document.getElementsByName('chek');
    let n=checkboxes.length
    for(let i=0;i<n;i++) {
      if(checkboxes[i].checked==false)
      {
        a=a+1;
      }
    }
    if(a==0)
    {
        $("[name=all]").prop('checked', true);
    }
    else
    {
        $("[name=all]").prop('checked', false);
    }
})
function toggle(source) {
    checkboxes = document.getElementsByName('chek');
    for(var i=0, n=checkboxes.length;i<n;i++) {
      checkboxes[i].checked = source.checked;
    }
  }
{% endblock %}

employer/templates/update_emp.html
{% extends 'emp_base.html' %}

{% block title %}
<title>mpower - Update Employers</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <form class="col-6 mx-auto p-3 card shadow-lg" method="post" enctype="multipart/form-data">
       {% csrf_token %}
        <h2>Update Employer</h2>
        <hr>

        <div class="mb-3">
         <label for="ename" class="form-label">Employer Name</label>
         <input type="text" class="form-control" name="ename" value="{{emp.ename}}">
       </div>

       <div class="mb-3">
         <label for="etype" class="form-label">Employer Industry</label>
         <input type="text" class="form-control" name="etype" value="{{emp.etype}}">
       </div>

       <div class="mb-3">
         <label for="eaddress" class="form-label">Employer Address</label>
         <input type="text" class="form-control" name="address" value="{{emp.address}}">
       </div>

       <div class="mb-3">
         <label for="ephn" class="form-label">Employer Phone no</label>
         <input type="text" class="form-control" name="phone" value="{{emp.phone}}">
       </div>

       <div class="form-group mb-3">
           <label for="logo">Employer logo Image</label>
           <input name="logo" type="file" class="form-control">
       </div>

       <div class="mb-3">
           <label for="website" class="form-label">Employer Website</label>
           <input type="text" class="form-control" name="website" value="{{emp.website}}">
       </div>

       <div class="mb-3">
           <label for="yearfounded" class="form-label">Year Founded</label>
           <input type="number" class="form-control" name="yearfounded" value="{{emp.yearfounded}}">
       </div>
 
       <button type="submit" class="btn btn-primary">Update Employer</button>
     </form>
</div>
{% endblock %}