candidate/urls.py
from . import views
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'candidate'

urlpatterns = [
	path('', views.dashboard, name ='dashboard'),
	path('jobapp/', views.jobapp, name='jobapp'),
	path('count_inbox/', views.count_inbox, name='count_inbox'),
	path('edit_profile/', views.edit_profile, name='edit'),
    path('get_o/', views.get_o, name='get_o'),
    path('post_o/', views.post_o, name='post_o'),
    path('upd_phone/', views.upd_phone, name='upd_phone'),
	path('change/', views.change, name='change'),
	path('onboarding/', views.onboarding, name='onboarding'),
	path('favjobs/', views.favjobs, name='favjobs'),
	path('favjobs/jobapp/', views.jobapp, name='jobapp'),
	path('edit_profile/add_skill/', views.add_skill, name='add_skill'),
	path('edit_profile/add_exp/', views.add_exp, name='add_exp'),
	path('edit_profile/add_edu/', views.add_edu, name='add_edu'),
	path('edit_profile/add_training/', views.add_training, name='add_training'),
	path('edit_profile/delete_exp/', views.delete_exp, name='delete_exp'),
	path('edit_profile/delete_skill/', views.delete_skill, name='delete_skill'),
	path('edit_profile/delete_edu/', views.delete_edu, name='delete_edu'),
	path('edit_profile/delete_training/', views.delete_training, name='delete_training'),
	path('edit_exp/', views.edit_exp, name='edit_exp'),
	path('edit_edu/', views.edit_edu, name='edit_edu'),
	path('update_salary/', views.update_salary, name='update_salary'),
	path('edit_training/', views.edit_training, name='edit_training'),
	path('applications/', views.applications, name='applications'),
	path('applications/jobapp/', views.jobapp, name='jobapp'),
	path('under_development/', views.under_development, name='under_development'),
	path('inbox/', views.inbox, name='inbox'),
	path('notifications/', views.notifications, name='notifications'),
	path('<int:pk2>/', views.employer, name='employer'),
	path('<int:pk2>/startconver/<pk3>/', views.startconver, name='startconver'),
	path('<int:pk2>/startconver/<pk3>/send', views.send, name='send'),
	path('inbox/sendfrom/', views.sendfromcand, name="sendfrom"),
	path('inbox/fetchmess/', views.fetchmess, name="fetchmess"),
	path('inbox/seenmes/', views.seenmes, name='seenmes'),
	path('resume/', views.resume, name='resume'),
	path('suggestions/', views.suggestions, name='suggestions'),
	path('suggestions/jobapp/', views.jobapp, name='jobapp'),
	path('thread/', views.thread, name='thread'),
	path('company/', views.company, name='company'),
	path('tests/', views.tests, name='tests'),
	path('attempt/<int:pk2>/<int:pk3>/', views.attempt, name='attempt'),
	path('submit/', views.submit, name='submit'),
    path('interviews/', views.interviews, name='interviews'),
    path('get_interview/', views.get_interview, name='get_interview'),
    path('feed_get/', views.feed_get, name='feed_get'),
	path('templates/', views.templates, name='templates'),
    path('get_template/', views.get_template, name='get_template'),
    path('set_step/', views.set_step, name='set_step'),
    path('job_change/', views.job_change, name='job_change'),
    path('job_change/jobapp/', views.jobapp, name='jobapp'),
    path('feedback/<int:pk1>/', views.feedback, name='feedback'),
	path('get_mocks/', views.get_mocks, name='get_mocks'),
	path('applications/attempt_mock/<int:pk1>', views.attempt_mock, name='attempt_mock'),
	path('submit_mock/', views.submit_mock, name='submit_mock'),
	path('upload_resume/', views.upload_resume, name='upload_resume'),
	path('logout/', views.logout, name='logout')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employer/urls.py
from . import views
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'employer'

urlpatterns = [
	path('', views.dashboard, name='cdashboard'),
	path('inbox_count/', views.inbox_count, name='inbox_count'),
	path('newjob/', views.newjob, name='newjob'),
	path('edit_profile/', views.edit, name='cedit'),
    path('get_ot/', views.get_ot, name='get_ot'),
    path('post_ot/', views.post_ot, name='post_ot'),
    path('cupd_phone/', views.cupd_phone, name='cupd_phone'),
	path('manage_job/', views.manage, name='manage'),
	path('candidates/', views.candidates, name='candidates'),
	path('subscriptions/', views.subscriptions, name='subscriptions'),
	path('change_pass/', views.change_pass, name='change_pass'),
	path('cinbox/', views.cinbox, name='cinbox'),
	path('cinbox/sendmess/', views.sendmess, name="sendmess"),
	path('cinbox/fetch/', views.fetch, name="fetch"),
	path('cinbox/seen/', views.seen, name='seen'),
	path('cinbox/delete/', views.delete_mess, name='delete_mess'),
	path('createthread/', views.createthread, name='createthread'),
	path('cnotifications/', views.cnotifications, name='cnotifications'),
	path('manage_job/cjobapp/', views.jobapp, name='cjobapp'),
	path('edit_job/', views.edit_job, name='edit_job'),
	path('get_candidate', views.get_candidate, name='get_candidate'),
	path('get_cands/', views.get_cands, name='get_cands'),
	path('cand_suggest/', views.cand_suggest, name='cand_suggest'),
    path('pending_actions/', views.pending_actions, name='pending_actions'),
    path('pending_actions/cjobapp/', views.jobapp, name='cjobapp'),
	path('quiz/cjobapp/', views.jobapp, name='cjobapp'),
	path('show_tests/', views.show_tests, name='show_tests'),
	path('create_test', views.create_test, name='test'),
	path('schedule/', views.schedule, name='schedule'),
	path('test_info/', views.test_info, name='test_info'),
	path('get_results/', views.get_results, name='get_results'),
    path('schedule_interview/', views.schedule_interview, name='schedule_interview'),
    path('all_interviews/', views.all_interviews, name='all_interviews'),
	path('all_templates/', views.all_templates, name='all_templates'),
    path('create_temp/', views.create_temp, name='create_temp'),
    path('get_template/', views.get_template, name='get_template'),
	path('schedule_temp/', views.schedule_temp, name='schedule_temp'),
    path('edit_template/<int:pk2>/', views.edit_template, name='edit_template'),
    path('get_temp_details/', views.get_temp_details, name='get_temp_details'),
    path('get_all_steps/<int:pk2>/', views.get_all_steps, name='get_all_steps'),
    path('delastep/<int:pk2>/', views.delastep, name='delastep'),
    path('all_steps/', views.all_steps, name='all_steps'),
    path('create_step/', views.create_step, name='create_step'),
    path('get_step/', views.get_step, name='get_step'),
    path('edit_step/', views.edit_step, name='edit_step'),
    path('done/', views.done, name='done'),
    path('get_link/', views.get_link, name='get_link'),
	path('logout/', views.logout, name='clogout'),
	path('suggest/', views.suggest, name='suggest'),
	path('request_cand/', views.requestCand, name='requestCand'),
	path('interview_complete/', views.interview_complete, name='interview_complete'),
	path('panel_request/', views.panel_request, name='panel_request'),
	path('edit_test/', views.edit_test, name='edit_test'),
	path('resume_feedback/', views.resume_feedback, name='resume_feedback'),
	path('get_cand_name/', views.get_cand_name, name='get_cand_name'),
	path('matchPerChange/', views.matchPerChange, name='matchPerChange'),
	path('resume_link/', views.resume_link, name='resume_link'),
	path('screening_questions/', views.screening_questions, name='screening_questions'),
	path('under_development/', views.under_development, name='under_development'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobster/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('candidate/<int:pk>/', include('candidate.urls', namespace= 'candidate')),
    path('employer/<int:pk>/', include('employer.urls', namespace= 'employer')),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace= 'mpoweradmin')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
 ] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

# handler404 = 'main.views.error_404_view'

main/urls.py
from . import views
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
# from jobster import settings

app_name = 'main'

urlpatterns = [
	path('', views.index, name ='index'),
	path('blog/', views.blog, name ='blog'),
	path('about_us/', views.about_us, name ='about_us'),
	path('pricing/', views.pricing, name ='pricing'),
	path('contact_us/', views.contact_us, name ='contact_us'),
	path('faqs/', views.faqs, name ='faqs'),
	path('signin/', views.signin, name ='signin'),
	path('signup/', views.signup, name ='signup'),
	path('user_login/', views.user_login, name ='user_login'),
	path('admin_login/', views.admin_login, name ='admin_login'),
	path('register/', views.register, name ='register'),
	path('admin_register/', views.admin_register, name ='admin_register'),
    path('subscribe/', views.subscribe, name='subscribe'),
	path('jobs/', views.findjobs, name ='jobs'),
	path('seminars/', views.seminars, name ='seminars'),
	path('companies/', views.companies, name ='companies'),
	path('candidates/', views.candidates, name ='candidates'),
	path('postjob/', views.postjob, name ='postjob'),
    path('get_job/', views.get_job, name='get_job'),
    path('give_feedback/<int:pk>/', views.give_feedback, name='give_feedback'),
    path('give_feed/<int:pk>/', views.give_feed, name='give_feed'),
	path('profile_completion/<int:pk>/', views.profile_completion, name="profilecompletion"),
	path('emp_completion/<int:pk>/', views.emp_completion, name="emp_completion"),
	path('admin_completion/<int:pk>/', views.admin_completion, name="admin_completion"),
	path('admin_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('admin_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('profile_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('profile_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('emp_completion/<int:pk>/get_otp/', views.get_otp, name='eget_otp'),
	path('emp_completion/<int:pk>/post_otp/', views.verify_otp, name='everify_otp'),
	path('singlejob/<int:pk2>/', views.singlejob, name='singlejob'),
	path('singleseminar/<int:pk1>/', views.singleseminar, name='singleseminar'),
	path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('password_reset_confirm/<str:email_encoded>/<str:token>/<str:timestamp>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('singlecompany/<int:pk2>/', views.singlecompany, name='singlecompany'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace = 'mpoweradmin')),
] 

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Emp_Manage(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True, blank=True),
    ename = models.CharField(max_length=100, default=None, null=True)
    etype = models.CharField(max_length=100, default=None, null=True)
    address = models.CharField(max_length=200, default=None, null=True)
    phone = models.CharField(max_length=100, default=None, null=True)
    logo = models.ImageField(upload_to='logos/', default=None, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    yearfounded = models.CharField(max_length=10, default=None, null=True)

candidate/templates/password-candidate.html
{% extends 'candidate-index.html' %}

{% block title %}
<title>mpower - Candidate dashboard - Change password</title>
{% endblock %}

{% block content %}
{% load static %}
<div class="pxp-dashboard-content-details">
    {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  
         <script>alert('{{ message }}')</script>
        {% endif %}
        {% endfor %}
    {% endif %}
    <h1>Change Password</h1>
    <p class="pxp-text-light">Choose a new account password.</p>

    <form method="post">
        {% csrf_token %}
        <div class="row mt-4 mt-lg-5">
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="pxp-candidate-old-password" class="form-label">Old password</label>
                    <input type="password" id="pxp-candidate-old-password" class="form-control" placeholder="Enter old password" name="old">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="pxp-candidate-new-password" class="form-label">New password</label>
                    <input type="password" id="pxp-candidate-new-password" class="form-control" placeholder="Enter new password"  name="new">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label for="pxp-candidate-new-password-repeat" class="form-label">New password repeat</label>
                    <input type="password" id="pxp-candidate-new-password-repeat" class="form-control" placeholder="Repeat new password" name="cnew">
                </div>
            </div>
        </div>

        <div class="mt-4 mt-lg-5">
            <button class="btn rounded-pill pxp-section-cta" type="submit">Save New Password</button>
        </div>
    </form>
</div>
{% endblock content %}

{% block script %}
$(document).ready(function () {
    $('#das').removeClass('pxp-active');
    $('#edi').removeClass('pxp-active');
    $('#app').removeClass('pxp-active');
    $('#fav').removeClass('pxp-active');
    $('#cha').addClass('pxp-active');
    $('#inb').removeClass('pxp-active');
    $('#not').removeClass('pxp-active');
    $('#res').removeClass('pxp-active');
    $('#fee').removeClass('pxp-active');
    $('#sug').removeClass('pxp-active');
    $('#tes').removeClass('pxp-active');
    $('#ins').removeClass('pxp-active');
    $('#jch').removeClass('pxp-active');
    $('#pla').removeClass('pxp-active');
})
{% endblock %}

candidate/templates/startconver.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ candidate.name }}
    {% for i in messages %}
    <div>
        {{ i.sender_user }}: {{ i.body }}
    </div>
    {% endfor %}
    <form method="post" action="{% url 'candidate:send' pk=pk pk2=pk2 pk3=pk3 %}">
        {% csrf_token %}
        <input type="text" name="message" />
        <button type="submit" class="btn btn-success" action="{% url 'candidate:send' pk=pk pk2=pk2 pk3=pk3 %}">Send</button>
    </form>
</body>
</html>

candidate/templates/templates-candidate.html
{% extends 'candidate-index.html' %}

{% block title %}
<title>mpower - Candidate dashboard - Templates</title>
{% endblock %}

{% block content %}
{% load static %}
{% load humanize %}


<div class="pxp-dashboard-content-details">
    {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  
         <script>alert('{{ message }}')</script>
        {% endif %}
        {% endfor %}
    {% endif %}
    <h1>Templates</h1>
    <p class="pxp-text-light">Detailed list of templates assigned to you.</p>

    <div class="mt-4 mt-lg-5">
        <div class="row justify-content-between align-content-center">
            <div class="col-auto order-2 order-sm-1">
                <div class="pxp-candidate-dashboard-jobs-bulk-actions mb-3">
                    {% comment %} <select class="form-select" name="act">
                        <option value="a">Bulk actions</option>
                        <option value="b">Delete</option>
                    </select>
                    <button class="btn ms-2" onclick="multiple()">Apply</button> {% endcomment %}
                </div>
            </div>
            <div class="col-auto order-1 order-sm-2">
                <div class="pxp-candidate-dashboard-jobs-search mb-3">
                    <div class="pxp-candidate-dashboard-jobs-search-results me-3">{{ count }} Templates</div>
                    <div class="pxp-candidate-dashboard-jobs-search-search-form">
                        <div class="input-group">
                            <span class="input-group-text" style="background: white"><span class="fa fa-search"></span></span>
                            <input type="text" class="form-control" placeholder="Search templates..." id="search">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle" id="table">
                <thead>
                    <tr>
                        {% comment %} <th class="pxp-is-checkbox" style="width: 1%;"><input type="checkbox" onClick="toggle(this)" class="form-check-input" name="all"></th> {% endcomment %}
                        <th>&nbsp;</th>
                        <th style="width: 28%;">Company</th>
                        <th style="width: 30%;">Link</th>
                        <th style="width: 30%;">Date<span class="fa fa-angle-up ms-3"></span></th>
                        <th style="width: 10%;">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in pe %}
                    <tr>
                        {% comment %} <td><input type="checkbox" name="chek" class="form-check-input" value={{ i.apply_id }}></td> {% endcomment %}
                        {% if i.logo %}
                        <td style="width: 4%;"><div class="pxp-candidate-dashboard-job-avatar pxp-cover"  style="background-image: url('{{ i.logo.url }}')"></div></td>
                        {% else %}
                        <td style="width: 4%;"><div class="pxp-candidate-dashboard-job-avatar pxp-cover"  style="background-image: url()"></div></td>
                        {% endif %}
                        <td>
                            <a href="#">
                                <div class="pxp-candidate-dashboard-job-title"onclick="companyload({{i.eid}})" data-bs-target="#pxp-company-modal" data-bs-toggle="modal">{{ i.ename }}</div>
                                {% if i.location %}
                                <div class="pxp-candidate-dashboard-job-location"><span class="fa fa-globe me-1"></span>{{ i.location }}</div>
                                {% else %}
                                <div class="pxp-candidate-dashboard-job-location"><span class="fa fa-globe me-1"></span>Not specified</div>
                                {% endif %}
                            </a>
                        </td>
                        <td><div class="pxp-candidate-dashboard-job-category"><a href={{i.link}} target="_blank" class="pxp-company-dashboard-job-date mt-1">{{ i.link }}</div></td></div>
                        <td><div class="pxp-candidate-dashboard-job-date mt-1">{{ i.date }}</div></td>
                        <td>
                            <div class="pxp-dashboard-table-options">
                                <ul class="list-unstyled" style="justify-content: center">
                                    <li><button title="Preview" onclick="interviewload({{i.eid}})" data-bs-target="#pxp-interview-modal" data-bs-toggle="modal"><span class="fa fa-eye"></span></button></li>
                                    {% if i.isdone %}
                                    <li><button title="Feedback info"  ><a href="{% url 'candidate:feedback' pk i.int_id %}"><span class="fa fa-comment"></span></a></button></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="row mt-4 mt-lg-5 justify-content-between align-items-center">
                <div class="col-auto">
                    <nav class="mt-3 mt-sm-0" aria-label="Applications list pagination">
                        <ul class="pagination pxp-pagination">
                            {% if count >= 6 %}
                            {% if pe.has_previous %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{pe.previous_page_number}}" class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{pe.previous_page_number}}" class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                {% endif %}
                            {% endif %}

                            {% if pe.number|add:'-4' > 1 %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.number|add:'-5' }}" class="page-link">&hellip;</a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{ pe.number|add:'-5' }}" class="page-link">&hellip;</a></li>
                                {% endif %}
                            {% endif %}

                            {% for i in pe.paginator.page_range %}
                                {% if pe.number == i %}
                                    <li class="page-item active" aria-current="page">
                                        <span style="padding: 0.7rem" class="page-link">{{pe.number}}</span>
                                    </li>
                                {% elif i > pe.number|add:'-5' and i < pe.number|add:'5' %}
                                    {% if GET_params %}
                                    <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ i }}" class="page-link">{{i}}</a></li>
                                    {% else %}
                                    <li class="page-item"><a style="padding: 0.7rem" href="?page={{ i }}" class="page-link">{{i}}</a></li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}

                            {% if pe.paginator.num_pages > pe.number|add:'4' %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.number|add:'5' }}" class="page-link">&hellip;</a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{ pe.number|add:'5' }}" class="page-link">&hellip;</a></li>
                                {% endif %}
                            {% endif %}

                            {% if pe.has_next %}
                                {% if GET_params %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?{{GET_params.urlencode}}&amp;page={{ pe.next_page_number }}" class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li class="page-item"><a style="padding: 0.7rem" href="?page={{pe.next_page_number}}" class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                {% endif %}
                            {% endif %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade pxp-user-modal" id="pxp-popup-modal" aria-hidden="true" aria-labelledby="popupModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <h5 class="modal-title text-center mt-4" id="c_na_me"></h5>
            </div>
            <hr>
            <div id="popups2">
            </div>
            <hr>
            <div id="int_reci" style="display: flex; justify-content: center; flex-wrap: wrap">
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
$(document).ready(function () {
    $('#das').removeClass('pxp-active');
    $('#edi').removeClass('pxp-active');
    $('#app').removeClass('pxp-active');
    $('#fav').removeClass('pxp-active');
    $('#cha').removeClass('pxp-active');
    $('#inb').removeClass('pxp-active');
    $('#not').removeClass('pxp-active');
    $('#res').removeClass('pxp-active');
    $('#fee').removeClass('pxp-active');
    $('#sug').removeClass('pxp-active');
    $('#tes').removeClass('pxp-active');
    $('#ins').removeClass('pxp-active');
    $('#jch').removeClass('pxp-active');
    $('#pla').addClass('pxp-active');
})

function feedbackload(id)
{
    $.ajax(
        {
            type:"GET",
            url: "{% url 'candidate:feed_get' pk=pk %}",
            data:{
                    'eid': id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function( data ) 
            {
                $('#c_na_me').text(data['info'].comname);
                let mainsec=document.getElementById('popups2');
                $('#popups2').empty();
                let p=document.createElement('p');
                if(data['info'].is_cand_done)
                {
                    p.innerHTML="Your feedback: "+data['info'].feed_cand
                }
                else
                {
                    p.innerHTML="Feedback link: "+data['info'].feed_cand;
                }
                mainsec.append(p);
                let main2=document.getElementById('int_reci');
                $('#int_reci').empty();
                let h6=document.createElement('h6');
                h6.innerHTML="Feedbacks Received";
                let hr=document.createElement('hr');
                main2.append(h6);
                main2.append(hr);
                let ul=document.createElement('ul');
                let lis=data['info'].feed_received;
                for(let i=0;i<lis.length;i++)
                {
                    let li=document.createElement('li');
                    li.innerHTML=lis[i];
                    ul.append(li);
                }
                main2.append(ul);
            }
    })
}

var $rows = $('#table tbody tr');
$('#search').keyup(function() {
    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
    $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
});

$("[name='chek']").change(function(){
    let a=0;
    checkboxes = document.getElementsByName('chek');
    let n=checkboxes.length
    for(let i=0;i<n;i++) {
      if(checkboxes[i].checked==false)
      {
        a=a+1;
      }
    }
    if(a==0)
    {
        console.log("True")
        $("[name=all]").prop('checked', true);
    }
    else
    {
        $("[name=all]").prop('checked', false);
    }
})
function delapp(id)
{
    $.ajax(
        {
            type:"POST",
            url: "",
            data:{
                    'apply_id': id,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function( data ) 
            {
                location.reload()
            }
    })
}

function multiple()
{
    let action=$("[name='act']").val();
    if(action=='a')
    {
        alert("Please select an appropriate action")
        return;
    }
    let ids=[];
    $("[name='chek']:checked").map(function () {
        ids.push(this.value);
    })
    if(ids.length==0)
    {
        alert("Please select at least one of the records to apply delete operation")
        return;
    }
    $.ajax(
        {
            type:"POST",
            url: "",
            data:{
                    'ids': ids,
                    'act': "delall",
                    csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function( data ) 
            {
                location.reload()
            }
    })
}

function toggle(source) {
    checkboxes = document.getElementsByName('chek');
    for(var i=0, n=checkboxes.length;i<n;i++) {
      checkboxes[i].checked = source.checked;
    }
  }
{% endblock %}