jobster/jobster/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

jobster/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace = 'main')),
    path('candidate/<int:pk>/', include('candidate.urls', namespace= 'candidate')),
    path('employer/<int:pk>/', include('employer.urls', namespace= 'employer')),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace= 'mpoweradmin')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
 ] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

# handler404 = 'main.views.error_404_view'

main/urls.py
from . import views
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
# from jobster import settings

app_name = 'main'

urlpatterns = [
	path('', views.index, name ='index'),
	path('blog/', views.blog, name ='blog'),
	path('about_us/', views.about_us, name ='about_us'),
	path('pricing/', views.pricing, name ='pricing'),
	path('contact_us/', views.contact_us, name ='contact_us'),
	path('faqs/', views.faqs, name ='faqs'),
	path('signin/', views.signin, name ='signin'),
	path('signup/', views.signup, name ='signup'),
	path('user_login/', views.user_login, name ='user_login'),
	path('admin_login/', views.admin_login, name ='admin_login'),
	path('register/', views.register, name ='register'),
	path('admin_register/', views.admin_register, name ='admin_register'),
    path('subscribe/', views.subscribe, name='subscribe'),
	path('jobs/', views.findjobs, name ='jobs'),
	path('seminars/', views.seminars, name ='seminars'),
	path('companies/', views.companies, name ='companies'),
	path('candidates/', views.candidates, name ='candidates'),
	path('postjob/', views.postjob, name ='postjob'),
    path('get_job/', views.get_job, name='get_job'),
    path('give_feedback/<int:pk>/', views.give_feedback, name='give_feedback'),
    path('give_feed/<int:pk>/', views.give_feed, name='give_feed'),
	path('profile_completion/<int:pk>/', views.profile_completion, name="profilecompletion"),
	path('emp_completion/<int:pk>/', views.emp_completion, name="emp_completion"),
	path('admin_completion/<int:pk>/', views.admin_completion, name="admin_completion"),
	path('admin_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('admin_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('profile_completion/<int:pk>/get_otp/', views.get_otp, name='get_otp'),
	path('profile_completion/<int:pk>/post_otp/', views.verify_otp, name='verify_otp'),
	path('emp_completion/<int:pk>/get_otp/', views.get_otp, name='eget_otp'),
	path('emp_completion/<int:pk>/post_otp/', views.verify_otp, name='everify_otp'),
	path('singlejob/<int:pk2>/', views.singlejob, name='singlejob'),
	path('singleseminar/<int:pk1>/', views.singleseminar, name='singleseminar'),
	path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('password_reset_confirm/<str:email_encoded>/<str:token>/<str:timestamp>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('singlecompany/<int:pk2>/', views.singlecompany, name='singlecompany'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('mpoweradmin/<int:pk>/', include('mpoweradmin.urls', namespace = 'mpoweradmin')),
] 

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .models import Admin, JobSeeker, Login, Employer, ResumeAnalysis, Jobs, LikedJobs, Application, Interview, Feedback, Newsletter, Course, AllSkills, RoleDetails, Notifications, Seminars, ScreeningQuestions
import random
import re
import requests
from django.contrib.auth.hashers import make_password, check_password
from django.core.mail import EmailMessage
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
import pyotp
import base64
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db.models import Count
from django.template.loader import render_to_string
from jobster import settings
import pandas as pd
import time
from urllib.parse import urlparse
from pyresparser import ResumeParser
from pdfminer3.layout import LAParams, LTTextBox
from pdfminer3.pdfpage import PDFPage
from pdfminer3.pdfinterp import PDFResourceManager
from pdfminer3.pdfinterp import PDFPageInterpreter
from pdfminer3.converter import TextConverter
import io
import random
from PIL import Image
from .Courses import ds_course, web_course, android_course, ios_course, uiux_course, resume_videos, interview_videos
import PyPDF2
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from sklearn.cluster import KMeans
import numpy as np
from itertools import groupby
from collections import defaultdict
from django.db.models import Count
import os
from django.core.files.base import ContentFile
from django.core.files import File
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponse
import json
from scipy.sparse import save_npz, load_npz
from io import BytesIO
# import plotly.express as px

from datetime import date, timedelta, datetime
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from itertools import chain

from django.db.models import Q
from django.db.models import Max, Min

from json import dumps
import PyPDF2
import string

from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.tokens import PasswordResetTokenGenerator
# from ip2geotools.databases.noncommercial import DbIpCity
import threading


@csrf_exempt
def index(request):
    if request.method == 'POST':
        if 'location' in request.POST:
            longitude = request.POST['longitude']
            latitude = request.POST['latitude']
        user = Login.objects.filter(email=request.POST['c_email'])
        if (len(user) == 0):
            return JsonResponse({'message': 'X'})
        else:

            if (check_password(request.POST['c_pass'], user[0].password)):
                if (request.POST['user'] == 'candidate' and JobSeeker.objects.filter(log_id=user[0].log_id)):
                    jobseeker = JobSeeker.objects.get(log_id=user[0].log_id)
                    if ((jobseeker.phone == None or jobseeker.phone == "" or len(jobseeker.phone) <= 4) and (jobseeker.location == None or jobseeker.location == "") and (jobseeker.experience == None or jobseeker.experience == "") and (jobseeker.skills == None or jobseeker.skills == "") and (jobseeker.basic_edu == None or jobseeker.basic_edu == "") and (jobseeker.master_edu == None or jobseeker.master_edu == "") and (jobseeker.other_qual == None or jobseeker.other_qual == "") and (jobseeker.dob == None or jobseeker.dob == "") and (jobseeker.Resume == "" or jobseeker.Resume == None) and (jobseeker.photo == "" or jobseeker.photo == None)):
                        urlval = "/profile_completion/"+str(user[0].log_id)+"/"
                        return JsonResponse({'message': 'Y', 'url': urlval})
                    # return redirect('main:profilecompletion', pk=user[0].log_id)
                elif (request.POST['user'] == 'employer' and Employer.objects.filter(log_id=user[0].log_id)):
                    employer = Employer.objects.get(log_id=user[0].log_id)
                    if ((employer.etype == None or employer.etype == "") and (employer.industry == None or employer.industry == "") and (employer.address == None or employer.address == "") and (employer.pincode == None or employer.pincode == "") and (employer.executive == None or employer.executive == "") and (employer.phone == None or employer.phone == "" or len(employer.phone) <= 4) and (employer.location == None or employer.location == "") and (employer.profile == None or employer.profile == "") and (employer.logo == "" or employer.logo == None)):
                        urlval = "/emp_completion/"+str(user[0].log_id)+"/"
                        return JsonResponse({'message': 'Y', 'url': urlval})

                else:
                    return JsonResponse({'message': 'X'})
                request.session['email'] = request.POST['c_email']
                request.session['password'] = user[0].password
                user[0].status = 1
                user[0].save()
                if (request.POST['user'] == 'candidate'):
                    empls = JobSeeker.objects.get(log_id=user[0].log_id)
                    request.session['name'] = empls.name
                    request.session['pk'] = empls.user_id
                    request.session['type'] = "c"
                    if (empls.photo):
                        request.session['photo'] = empls.photo.url
                    jobid = request.POST.get('jobid')
                    if jobid:
                        urlval = "/singlejob/"+jobid+"/"
                    else:
                        urlval = "/candidate/"+str(jobseeker.user_id)+"/"

                    # print(request.POST['jobid'])
                    return JsonResponse({'message': 'Y', 'url': urlval})
                else:
                    emp = Employer.objects.get(log_id=user[0].log_id)
                    request.session['name'] = emp.ename
                    request.session['pk'] = emp.eid
                    request.session['type'] = "e"
                    if (emp.logo):
                        request.session['photo'] = emp.logo.url
                    urlval = "/employer/"+str(emp.eid)+"/"

                    return JsonResponse({'message': 'Y', 'url': urlval})
            else:
                return JsonResponse({'message': 'X'})

    jobs = Jobs.objects.all()
    typ = jobs.values('fnarea').annotate(
        Count('fnarea')).order_by('-fnarea__count')[:6]
    coms = jobs.values('eid').annotate(
        Count('eid')).order_by('-eid__count')[:6]
    vals = [{'fnarea': i['fnarea'], 'count': i['fnarea__count']} for i in typ]

    try:
        user_ip = request.META.get('REMOTE_ADDR')
        url = f"https://ipinfo.io/{user_ip}/json"
        response = requests.get(url)
        data = response.json()
        user_city = data.get('city', 'City Not Found')
    except Exception as e:
        print(f"Error fetching user IP: {e}")
        user_city = 'City Not Found'

    # Fetch seminars ordered by latest posted date
    seminars_in_ascending_order = Seminars.objects.order_by('-created_date')

    # Fetch distinct locations and titles
    locations = list(jobs.order_by().values_list(
        'location', flat=True).distinct())
    titles = list(jobs.order_by().values_list('title', flat=True).distinct())

    jobs_info = [
        {
            'fnarea': job.fnarea,
            'title': job.title,
            'location': job.location,
            'type': job.jobtype,
            'date': job.postdate,
            'name': job.eid.ename,
            'jobid': job.jobid,
            'logo': job.eid.logo if job.eid.logo else None,
            'eid': job.eid.eid
        }
        for job in jobs.order_by('-num_of_visits')[:8]
    ]

    coms_info = [
        {
            'name': emp.ename,
            'eid': emp.eid,
            'logo': emp.logo if emp.logo else None,
            'info': emp.profile,
            'count': count['eid__count']
        }
        for count in coms
        for emp in Employer.objects.filter(eid=count['eid'])
    ]

    return render(request, 'index.html', {
        'locations': locations,
        'titles': titles,
        'title': dumps([title for title in titles]),
        'vals': vals,
        'jobs': jobs_info,
        'coms': coms_info,
        'loc': locations,
        'total': len(jobs),
        'seminars': seminars_in_ascending_order
    })


def save_resume_vector_matrix_all():
    all_entries = ResumeAnalysis.objects.all()

    jobseeker_instances = defaultdict(list)

    for entry in all_entries:
        jobseeker_instances[entry.jobseeker_id].append(entry)

    for jobseeker_id, instances in jobseeker_instances.items():
        if len(instances) > 1:
            instances_to_delete = instances[1:]
            for instance in instances_to_delete:
                instance.delete()
    try:
        vectorizer = CountVectorizer()
        jobSeeker = JobSeeker.objects.all()
        i = 0
        for job_seeker in jobSeeker:
            try:
                important_data_jobseeker = f"{job_seeker.location} {job_seeker.experience} {job_seeker.skills} {job_seeker.basic_edu} {job_seeker.master_edu} {job_seeker.other_qual} {job_seeker.cursal} {job_seeker.expsal} {job_seeker.notice_period}"
                resume_pdf_file = job_seeker.Resume.path
                resume_text = extract_text_from_pdf(resume_pdf_file)

main/templates/admin-login.html
{% load static %}
{% block content %}
<!doctype html>
<html lang="en" class="pxp-root">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600;700&display=swap" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <title>mpower - Sign in</title>
    </head>
    <style>
        body
        {
            overflow-y: hidden;
        }
        .pxp-header {
            background-color: rgba(1,1,1,0.1) !important;
        }
        .pxp-nav .pxp-usernav
        {
            display: none !important; 
        }
        .btn-sign
        {
            margin: auto;
        width: 100%;
        }
        .google-button {
        display: flex; /* Use flexbox to layout the button's content */
        align-items: center; /* Center the button's content vertically */
        justify-content: center; /* Add space between the logo and text */
        background-color: white; /* Set the button's background color to white */
        color: black; /* Set the button's text color to black */
        padding: 10 15px; /* Add some padding to the button */
        border: 1px solid darkgray; /* Add some padding to the buttonSet the button's height */
        font-size: 18px; /* Set the font size of the button's text */
        }

/* Style the Google logo */
        .google-button .logo {
        width: 30px; /* Set the logo's width */
        height: 30px; /* Set the logo's height */
        background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu1PJmT_THldF0n5APcmt9p10utgu6KSw4cH2fQ5Xhpw&s'); /* Set the logo's background image */
        background-size: contain; /* Scale the logo to fit inside the button */
        background-repeat: no-repeat; /* Don't repeat the logo's background image */
        margin-right: 15px; /* Add some space between the logo and text */
        }
        .google-button:hover {
        color:#357ae8;
        background-color: white !important;/* A darker shade of Google's blue color */
        }

        .emp_btn:hover
        {
            background: var(--pxpMainColor) !important;
            color: lightblue;
        }
    </style>
    
    <body>
        {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  
         <script>alert('{{ message }}')</script>
        {% endif %}

        {% endfor %}

        {% endif %}
        
        <div class="pxp-preloader"> 
    <div class="pxp-logo">
    <a href="index.html" class="pxp-animate" style=" font-size:35px !important;"><span style="color: var(--pxpMainColor);">un</span>tappped</a>
</div></div>

<header class="pxp-header fixed-top">
    <div class="pxp-container">
        <div class="pxp-header-container">
            <div class="pxp-logo">
                <a href="{% url 'main:index' %}" class="pxp-animate"><span style="color: var(--pxpMainColor)">un</span>tappped</a>
            </div>
            

            <!-- Desktop Header Starts -->
            
            <nav class="pxp-user-nav d-none d-sm-flex">
                
                {% if 'session_id' in request.session %}
               <div class="dropdown pxp-user-nav-dropdown">
                    <a href="index.html" class="dropdown-toggle" data-bs-toggle="dropdown">
                        <div class="pxp-user-nav-avatar pxp-cover" style="background-image: url(/static/images/user.png);"></div>
                        <div class="pxp-user-nav-name d-none d-md-block">Derek Cotner</div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="candidate-dashboard.html">Dashboard</a></li>
                        <li><a class="dropdown-item" href="candidate-dashboard-profile.html">Edit profile</a></li>
                        <li><a class="dropdown-item" href="index.html">Logout</a></li>
                    </ul>
                </div>
             
                {% endif%}
            </nav>
        </div>
    </div>
</header>


        

        

        <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
            
            <div class="row align-items-center pxp-sign-hero-container">
                <div class="col-xl-6 pxp-column">
                    <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                        <img src="{% static 'images/signin-big-fig.png' %}" alt="Sign In">
                        <h1 class="mt-4 mt-lg-5">Welcome back!</h1>
                    </div>
                </div>
                <div class="col-xl-6 pxp-column pxp-is-light">
                    <div class="pxp-sign-hero-form pb-100 pt-100">
                        <div class="row justify-content-center">
                            <div class="col-lg-6 col-xl-7 col-xxl-5">
                                <div class="pxp-sign-hero-form-content">
                                    <h5 class="text-center">Admin Log-In</h5>
                                    <form class="mt-4" method="post" action="{% url 'main:admin_login' %}">
                                        {% csrf_token %}
                                        <div class="form-floating mb-3">
                                            <input type="email" class="form-control" id="pxp-signin-page-email" name="email" placeholder="Email address">
                                            <label for="pxp-signin-page-email">Email address</label>
                                            <span class="fa fa-envelope-o"></span>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input type="password" class="form-control" id="pxp-signin-page-password" name="pass" placeholder="Password">
                                            <label for="pxp-signin-page-password">Password</label>
                                            <span class="fa fa-lock"></span>
                                        </div>
                                        <input type="submit" value="Continue" class="btn btn-sign rounded-pill pxp-modal-cta">
                                        <hr>
                                        <button class="btn btn-sign rounded-pill pxp-modal-cta google-button" >
                                            <div class="logo">
                                            </div>Sign in with Google

                                          </button>
                                          


                                        <div class="mt-4 text-center pxp-sign-hero-form-small">
                                            <a href="#" class="pxp-modal-link">Forgot password</a>
                                        </div>

                                        
                                        <div class="mt-4 text-center pxp-sign-hero-form-small">
                                            New to mpower? <a href="{% url 'main:admin_register' %}">Create an account</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>



       

       

        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/nav.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>
{% endblock %}

main/templates/sign-in.html
{% load static %}
{% block content %}
<!doctype html>
<html lang="en" class="pxp-root">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600;700&display=swap" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <title>mpower - Sign in</title>
    </head>
    <style>
        body
        {
            overflow-y: hidden;
        }
        .pxp-header {
            background-color: rgba(1,1,1,0.1) !important;
        }
        .pxp-nav .pxp-usernav
        {
            display: none !important; 
        }
        .btn-sign
        {
            margin: auto;
        width: 100%;
        }
        .google-button {
        display: flex; /* Use flexbox to layout the button's content */
        align-items: center; /* Center the button's content vertically */
        justify-content: center; /* Add space between the logo and text */
        background-color: white; /* Set the button's background color to white */
        color: black; /* Set the button's text color to black */
        padding: 10 15px; /* Add some padding to the button */
        border: 1px solid darkgray; /* Add some padding to the buttonSet the button's height */
        font-size: 18px; /* Set the font size of the button's text */
        }

/* Style the Google logo */
        .google-button .logo {
        width: 30px; /* Set the logo's width */
        height: 30px; /* Set the logo's height */
        background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu1PJmT_THldF0n5APcmt9p10utgu6KSw4cH2fQ5Xhpw&s'); /* Set the logo's background image */
        background-size: contain; /* Scale the logo to fit inside the button */
        background-repeat: no-repeat; /* Don't repeat the logo's background image */
        margin-right: 15px; /* Add some space between the logo and text */
        }
        .google-button:hover {
        color:#357ae8;
        background-color: white !important;/* A darker shade of Google's blue color */
        }

        .emp_btn:hover
        {
            background: var(--pxpMainColor) !important;
            color: lightblue;
        }
    </style>
    
    <body>
        {% if messages %}
        {% for message in messages %}
         {% if message.tags %}  
         <script>alert('{{ message }}')</script>
        {% endif %}

        {% endfor %}

        {% endif %}
        
        <div class="pxp-preloader"> 
    <div class="pxp-logo">
    <a href="index.html" class="pxp-animate" style=" font-size:35px !important;"><span style="color: var(--pxpMainColor);">un</span>tappped</a>
</div></div>

<header class="pxp-header fixed-top">
    <div class="pxp-container">
        <div class="pxp-header-container">
            <div class="pxp-logo">
                <a href="{% url 'main:index' %}" class="pxp-animate"><span style="color: var(--pxpMainColor)">un</span>tappped</a>
            </div>
            

            <!-- Desktop Header Starts -->
            
            <nav class="pxp-user-nav d-none d-sm-flex">
                
                {% if 'session_id' in request.session %}
               <div class="dropdown pxp-user-nav-dropdown">
                    <a href="index.html" class="dropdown-toggle" data-bs-toggle="dropdown">
                        <div class="pxp-user-nav-avatar pxp-cover" style="background-image: url(/static/images/user.png);"></div>
                        <div class="pxp-user-nav-name d-none d-md-block">Derek Cotner</div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="candidate-dashboard.html">Dashboard</a></li>
                        <li><a class="dropdown-item" href="candidate-dashboard-profile.html">Edit profile</a></li>
                        <li><a class="dropdown-item" href="index.html">Logout</a></li>
                    </ul>
                </div>
                {% else %}
                <!--<div class="dropdown pxp-user-nav-dropdown " style="color:black;">
                    <a href="index.html" class="dropdown-toggle btn rounded-pill pxp-nav-btn emp_btn" data-bs-toggle="dropdown">
                        
                        <div class="pxp-user-nav-name d-none d-md-block">For Employers</div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="candidate-dashboard.html">Employer Login</a></li>
                        <li><a class="dropdown-item" href="candidate-dashboard-profile.html">Sales Enquiry</a></li>
                       
                    </ul>
                </div>-->
                {% endif%}
            </nav>
        </div>
    </div>
</header>


        

        

        <section class="pxp-hero vh-100" style="background-color: var(--pxpMainColorLight);">
            
            <div class="row align-items-center pxp-sign-hero-container">
                <div class="col-xl-6 pxp-column">
                    <div class="pxp-sign-hero-fig text-center pb-100 pt-100">
                        <img src="{% static 'images/signin-big-fig.png' %}" alt="Sign In">
                        <h1 class="mt-4 mt-lg-5">Welcome back!</h1>
                    </div>
                </div>
                <div class="col-xl-6 pxp-column pxp-is-light">
                    <div class="pxp-sign-hero-form pb-100 pt-100">
                        <div class="row justify-content-center">
                            <div class="col-lg-6 col-xl-7 col-xxl-5">
                                <div class="pxp-sign-hero-form-content">
                                    <h5 class="text-center">Candidate Sign-In</h5>
                                    <form class="mt-4" method="post" action="{% url 'main:user_login' %}">
                                        {% csrf_token %}
                                        <div class="form-floating mb-3">
                                            <input type="email" class="form-control" id="pxp-signin-page-email" name="email" placeholder="Email address">
                                            <label for="pxp-signin-page-email">Email address</label>
                                            <span class="fa fa-envelope-o"></span>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input type="password" class="form-control" id="pxp-signin-page-password" name="pass" placeholder="Password">
                                            <label for="pxp-signin-page-password">Password</label>
                                            <span class="fa fa-lock"></span>
                                        </div>
                                        <input type="submit" value="Continue" class="btn btn-sign rounded-pill pxp-modal-cta">
                                        <hr>
                                        <button class="btn btn-sign rounded-pill pxp-modal-cta google-button" >
                                            <div class="logo"></div>
                                            Sign in with Google
                                          </button>
                                          


                                        <div class="mt-4 text-center pxp-sign-hero-form-small">
                                            <a href="#" class="pxp-modal-link">Forgot password</a>
                                        </div>

                                        
                                        <div class="mt-4 text-center pxp-sign-hero-form-small">
                                            New to mpower? <a href="{% url 'main:register' %}">Create an account</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>



       

       

        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/nav.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>
{% endblock %}